### ISSUE TITLE
problems about the experiment formulation

### ISSUE THREAD

**Issue by hhjj233** [MediaBrain-SJTU/SyncNet#2]
Thank you for your great work! I wonder whether you formed the experiments with only focusing on V2V situation in this paper. Since you mentioned the net is trained and validated with V2X-sim dataset. However you did not mention whether the RSU/infrastructure is involved.

**Comment by Chezacar** [comment]
Our paper is based on the early version of V2X-Sim. Now we are working on the new version of V2X-Sim dataset, including V2V and V2I.

**Comment by hhjj233** [comment]
Thank you. That's helpful.
