### ISSUE TITLE
Can't find model file.

### ISSUE THREAD

**Issue by YueChuCheng** [MediaBrain-SJTU/SyncNet#4]
Thanks for the nice repo you provided, but sadly I can't find the `LA_disco.pth` mentioned in `test_LA.sh`,  hope you can share the model so that it will be easier to reproduce the result you say in the paper :)

**Comment by Chezacar** [comment]
Sorry for inconvenient. There are DiscoNet and SyncDisocNet examples of checkpoints when compress_level is set to be 2.
link: https://pan.baidu.com/s/1Ogxf7xRQuslcSow_amk2kw?pwd=0810 code: 0810

**Comment by YueChuCheng** [comment]
@Chezacar Thanks for your reply! But sorry I don't have  baidu account can you upload it on to other paltform? e.g. google drive

**Comment by YueChuCheng** [comment]
Solved!

**Comment by HuangZhe885** [comment]
> Sorry for inconvenient. There are DiscoNet and SyncDisocNet examples of checkpoints when compress_level is set to be 2. link: https://pan.baidu.com/s/1Ogxf7xRQuslcSow_amk2kw?pwd=0810 code: 0810

Dear author, thank you for your great work. Could you please share the LA_disco.pth and train_LA.sh file?

**Comment by Chezacar** [comment]
There are DiscoNet and SyncDisocNet examples of checkpoints when compress_level is set to be 2 in version 2.0 of V2X-Sim.
link: https://pan.baidu.com/s/1BdMg4LOHQ1tgjnB1Zblbyw?pwd=3vpq code: 3vpq

> > Sorry for inconvenient. There are DiscoNet and SyncDisocNet examples of checkpoints when compress_level is set to be 2. link: https://pan.baidu.com/s/1Ogxf7xRQuslcSow_amk2kw?pwd=0810 code: 0810
> 
> Dear author, thank you for your great work. Could you please share the LA_disco.pth and train_LA.sh file?

**Comment by scdrand23** [comment]
The link has expired. Can you share a new one, please?
