### ISSUE TITLE
Can not find the pretrained model

### ISSUE THREAD

**Issue by Henrry995** [MediaBrain-SJTU/SyncNet#6]
Thanks for the nice repo you provided, but sadly I can't find the LA_disco.pth mentioned in test_LA.sh, hope you can share the model so that it will be easier to reproduce the result you say in the paper :)

**Comment by Chezacar** [comment]
There are DiscoNet and SyncDisocNet examples of checkpoints when compress_level is set to be 2 in version 2.0 of V2X-Sim.
link: https://pan.baidu.com/s/1BdMg4LOHQ1tgjnB1Zblbyw?pwd=3vpq code: 3vpq

**Comment by Henrry995** [comment]
Thanks for your reply!
